TFP-5732 endrer tekster rundt opphør i innvilgelsesbrev foreldrepenger
navikt/fp-dokgen pull request #770
Opened 2024-09-26 10:25 UTC by palfi

2024-09-26 12:30 UTC, AnjaAalerud requested changes
Ser ok ut! Men må oppdatere test for ForeldrepengerInnvilgelseAvslagTest

2024-09-26 17:27 UTC, jolarsen approved these changes

2024-09-26 17:28 UTC, jolarsen reviewed
Trenger vi tilsvarende i FP-opphør?
Enn SVP innvilget / opphør ?

2024-09-27 06:33 UTC, palfi commented
> Trenger vi tilsvarende i FP-opphør? Enn SVP innvilget / opphør ?

svp og fp opphørsbrevene tror jeg fungerer, men svp innvilgelse har mangler ved opphør

2024-09-27 06:49 UTC, merged